### ISSUE TITLE
获取2100年后的指定节气日期报错了，好像不支持？

### ISSUE THREAD

**Issue by freemanercom** [waterbeside/lunisolar#15]
TypeError: Cannot read properties of undefined (reading 'toString')
    at Function.e.getYearTermDayList (/XXXXXXXXXXXXXXXXXXXXXXX/node_modules/lunisolar/dist/lunisolar.js:1:15821)
    at Function.e.findDate (/XXXXXXXXXXXXXXXXXXXXXXX/node_modules/lunisolar/dist/lunisolar.js:1:16308)

**Comment by freemanercom** [comment]
貌似2100后是个麻烦事... ,感谢 先关闭了
